name: stream_chat_persistence
homepage: https://github.com/GetStream/stream-chat-flutter
description: Official Stream Chat Persistence library. Build your own chat experience using Dart and Flutter.
version: 1.5.0
repository: https://github.com/GetStream/stream-chat-flutter
issue_tracker: https://github.com/GetStream/stream-chat-flutter/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.0.0
  meta: ^1.2.4
  moor: ^4.2.1
  mutex: ^2.0.0
  path: ^1.7.0
  path_provider: ^2.0.0
  sqlite3_flutter_libs: ^0.4.0+1
  stream_chat:
    git:
      # url: https://github.com/GetStream/stream-chat-flutter/
      # ref: f45fcd0bc281f20fa6eaf521c5de3e0153361055
      url: https://github.com/Sugihiru/stream-chat-flutter
      path: packages/stream_chat

dev_dependencies:
  build_runner: ^1.11.0
  moor_generator: ^4.2.1
  pedantic: ^1.9.2
  test: ^1.15.7
